name: build-libcec-unix
description: Builds libcec on Unix environments.

inputs:
  arch:
    description: The architecture being built.
    required: true
  build_type:
    description: The build type, either "Release" or "Debug".
    required: true
  libcec_version:
    description: The libcec version to build.
    required: true

outputs:
  binary_path:
    description: The freshly-built binary path.
    value: ${{ steps.set_output.outputs.binary_path }}

runs:
  using: composite
  steps:
    - name: Checkout libcec
      uses: actions/checkout@v4
      with:
        path: libcec
        repository: Pulse-Eight/libcec
        ref: libcec-${{ env.libcec_version }}
        submodules: recursive

    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@main

    - name: Setup Nix cache
      uses: DeterminateSystems/magic-nix-cache-action@main

    - name: Build libcec
      shell: bash
      working-directory: libcec
      run: ../build-macos.sh . '${{ matrix.build_type }}'

    - name: Extract binaries
      shell: bash
      working-directory: libcec
      run: |
        set -euxo pipefail
        mkdir -p libcec/dist
        cp -rf build/**/*.{a,so,dylib} '${{ github.workspace }}/libcec/dist'

    - name: Set output
      id: set_output
      shell: bash
      run: echo "binary_path=${{ github.workspace }}/libcec/dist" >> $GITHUB_OUTPUT
