name: Build

permissions:
  contents: write

env:
  libcec_version: 6.0.2
  visual_studio_version: 2019

on:
  push:
    branches:
      - main

jobs:
  build-windows:
    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        arch: [x86, amd64]
        build_type: [Release, Debug]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build libcec
        id: build_libcec
        uses: ./.github/actions/build-libcec-windows
        with:
          arch: ${{ matrix.arch }}
          build_type: ${{ matrix.build_type }}
          libcec_version: ${{ env.libcec_version }}
          visual_studio_version: ${{ env.visual_studio_version }}

      - uses: actions/upload-artifact@v4
        with:
          name: libcec-${{ env.libcec_version }}-windows-${{ matrix.arch }}-${{ matrix.build_type }}
          path: ${{ steps.build_libcec.outputs.binary_path }}
          if-no-files-found: error

  build-macos:
    runs-on: macos-latest

    strategy:
      fail-fast: false
      matrix:
        arch: [arm64]
        build_type: [Release, Debug]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build libcec
        id: build_libcec
        uses: ./.github/actions/build-libcec-unix
        with:
          build_type: ${{ matrix.build_type }}
          libcec_version: ${{ env.libcec_version }}

      - uses: actions/upload-artifact@v4
        with:
          name: libcec-${{ env.libcec_version }}-macos-${{ matrix.arch }}-${{ matrix.build_type }}
          path: ${{ steps.build_libcec.outputs.binary_path }}
          if-no-files-found: error
